version: '2'

services:
  web:
    restart: unless-stopped
    image: nginx:latest
    ports:
        - "80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
        - php
    links:
        - php
        - mariadb:mysql
        - redis
    environment:
        VIRTUAL_HOST: www.radio-solutions.local

  magerun:
    build: m2-cli
    environment:
       MAGE_ROOT_DIR: /var/www/html
       MAGE_VER: 1
    links:
       - mariadb:mysql
    volumes_from:
       - php

  php:
    build: php-7
    volumes:
        - ./web:/var/www/html

  mariadb:
    image: mariadb
    ports:
        - 3306
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=docker
     - MYSQL_USER=magento
     - MYSQL_PASSWORD=password
    restart: unless-stopped
    volumes:
     - ./database:/var/lib/mysql:rw

  redis:
    image: "redis:alpine"


